# NumPy Examples

- array operations
- matrix operations
- numpy made python a scientific language

In [1]:
import numpy as np

In [4]:
x = list(range(1, 1000))
y = [n + 1 for n in x]

In [9]:
x = np.array(range(1,1000))
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [10]:
x = np.arange(1, 1000)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [ ]:
x.

In [6]:
type(x)

numpy.ndarray

ndarray = n-dimensional array

    (tensor = n-dimensional array of only numbers)

### 5 components of a program
1. input
2. output
3. sequence
4. selection
5. iteration

In [11]:
x = np.arange(-1000, 1000)

In [13]:
mask = x > 950

is each element greater than 950?

In [14]:
mask

array([False, False, False, ...,  True,  True,  True])

In [16]:
x[mask]

array([951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963,
       964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976,
       977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989,
       990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [15]:
# how many numbers match the mask
mask.sum()

49

In [17]:
# sum all the numbers that match the mask (x > 950)
x[mask].sum()

47775

In [19]:
x[mask].mean()

975.0

In [20]:
higher_than_950 = x[mask]

In [21]:
higher_than_950.max()

999

In [22]:
higher_than_950.min()

951

In [27]:
higher_than_950.argmax() # argmax returns the index of the highest number

48

In [28]:
higher_than_950[higher_than_950.argmax()]

999

In [30]:
x = np.arange(-1000, 1000)
x[(x > 5) & (x % 2 == 0)] # single & for plural ands

array([  6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,
        32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
        58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
        84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108,
       110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134,
       136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160,
       162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186,
       188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212,
       214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238,
       240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264,
       266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290,
       292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316,
       318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342,
       344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 36

In [33]:
x = np.arange(-1000, 1000)
x[(x > 0) | (x % 2 == 0)] # single & for plural ands

array([-1000,  -998,  -996, ...,   997,   998,   999])

In [31]:
x = np.arange(-1000, 1000)
x = x[x > 0] # x where x is greater than 0
x = x[x % 2 == 0] # read this as select x where x > 0

In [32]:
x

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36